### ISSUE TITLE
上传步骤失败

### ISSUE THREAD

**Issue by G233** [zkqiang/tencent-cos-action#1]
![image](https://user-images.githubusercontent.com/39009225/75453255-9bb91100-59ae-11ea-9d36-daddb8dc039a.png)

**Comment by G233** [comment]
查看储存桶发现有个别文件上传成功了

**Comment by G233** [comment]
而且再次 PUSH action 不运行了

**Comment by zkqiang** [comment]
这个是 timeout 网络问题，我没办法解决...
